spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ds-our-sopt.corhws1nxyif.ap-northeast-2.rds.amazonaws.com/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: cnd961217
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE